MyProgramApp/urls.py
from django.urls import path
from . import views
from .views import (
    ProgramListView,
    program_create,
    program_detail,
    program_update,
    program_delete
)


app_name = 'MyProgramApp'

urlpatterns = [
    path('', views.ProgramListView.as_view(), name='program_list'),
    path('create/', views.program_create, name='program_create'),
    path('<int:pk>/', views.program_detail, name='program_detail'),
    path('<int:pk>/update/', views.program_update, name='program_update'),
    path('<int:pk>/delete/', views.program_delete, name='program_delete'),
]

project_02/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('DataBaseApp/', include('DataBaseApp.urls', namespace='DataBaseApp')),
    path('MyProgramApp/', include('MyProgramApp.urls', namespace='MyProgramApp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'MyProgramApp/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Выберите приложение:</h4>
                        <div class="d-grid gap-3 mt-4">
                            <a href="{% url 'MyProgramApp:program_list' %}" class="btn btn-primary btn-lg">
                                Приложение 1. Образовательная программа
                            </a>
                            <a href="{% url 'DataBaseApp:home' %}" class="btn btn-danger btn-lg">
                                Приложение 2. Я и мое обучение в Вышке
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>